
## Dynamic configuration
http:
  services:
    mockbin:
      loadBalancer:
        passHostHeader: false
        servers:
        - url: "http://mockbin.org"

# Mirror example
#    mirrored-api:
#      mirroring:
#        service: appv1
#        mirrors:
#        - name: appv2
#          percent: 10

  routers:
    mockbin:
      # https://docs.traefik.io/routing/routers/#rule
      rule: "PathPrefix(`/open`)"
      service: mockbin
      middlewares:
      - request-service-prefix

    mockbin-auth:
      rule: "PathPrefix(`/auth`)"
      service: mockbin
      middlewares:
      - request-service-prefix
      - key-auth
      entryPoints:
      - "internal"
      - "http"

  middlewares:
    request-service-prefix:
      addPrefix:
        prefix: "/requests"
    key-auth:
      basicAuth:
        realm: "Mockbin"
        users:
          - "bob:$apr1$BSlChtqX$Bv6T9QQ1riKXEEJZTHlmH."
        # usersFile: "/path/to/my/usersfile"

    # Other middledwares
    test-auth:
      forwardAuth:
        address: "https://authserver.com/auth"
    test-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "192.168.1.7"
        ipStrategy:
          depth: 2
    latency-check:
      circuitBreaker:
        expression: "LatencyAtQuantileMS(50.0) > 100"
    test-ratelimit:
      rateLimit:
        average: 100
        burst: 50
    test-retry:
      retry:
       attempts: 4


